### ISSUE TITLE
unsemantic sass does not run with leafo/scssphp

### ISSUE THREAD

**Issue by Aybee** [nathansmith/unsemantic#100]
Compilation of unsemantic sass files does not work with leafo/scssphp http://leafo.github.io/scssphp/

**First** it stops with messages of missing placeholder classes that should get extended.

name                 |path                                  |last changed       |line# |line
:---                 |:---                                  |:---               |:---   |:---
_unsemantic-vars.scss|unsemantic-master\assets\sass\partials|18.01.2018 02:02   |356    |@extend %grid-container;
_unsemantic-vars.scss|unsemantic-master\assets\sass\partials|18.01.2018 02:02   |364    |@extend %clear;
_unsemantic-vars.scss|unsemantic-master\assets\sass\partials|18.01.2018 02:02   |368    |@extend %clearfix;
_unsemantic-vars.scss|unsemantic-master\assets\sass\partials|18.01.2018 02:02   |378    |@extend %grid-parent;
_unsemantic-vars.scss|unsemantic-master\assets\sass\partials|18.01.2018 02:02   |384    |@extend %grid-offset;
_unsemantic-vars.scss|unsemantic-master\assets\sass\partials|18.01.2018 02:02   |405    |@extend %grid-columns-all;
_unsemantic-vars.scss|unsemantic-master\assets\sass\partials|18.01.2018 02:02   |414    |@extend %grid-columns-all;

I added the missing placeholders  in my _custom_vars.scss
```scss
%grid-container {
  content: '';
}
%clear {
  content: '';
}
%clearfix {
  content: '';
}
%grid-parent {
  content: '';
}
%grid-offset {
  content: '';
}
%grid-columns-all {
  content: '';
}
```
They must have at least one property.

**Second**: The output CSS is wrong. It creates mobile, tablet and desktop on all breakpoints. E.g.
```css
...
@media (max-width: 400px) {
  ...
  .mobile-grid-5,
  .tablet-grid-5,
  .grid-5 {
    float: left;
    width: 5%
  }
  ...
```
