### ISSUE TITLE
Column for the next row sometimes did not start on the left

### ISSUE THREAD

**Issue by Aybee** [nathansmith/unsemantic#102]
See here https://codepen.io/Aybee/pen/MGZXRz

How should we handle this behavior? If it's not possible I think I have to write my own CSS maybe with flex containers.

**Comment by nathansmith** [comment]
You'll want to use a clearing `<span>`, or similar element.

```
<div class="grid-X">…</div>

<span class="clear"></span>

<div class="grid-X">…</div>
```

Using the `hide-on-X` classes, this lets you granularly control where the breaks occur.

More info here…

https://github.com/nathansmith/unsemantic/issues/41#issuecomment-27580364

**Comment by Aybee** [comment]
Ok, so it seems to be the nature of floated elements and we need individual solutions. E.g. this in my case as the markup is generated by a CMS and I don't want to use a new individual template.
```css
.grid-33:nth-child(3n-2) {
  clear: both;
}
@media (min-width:768px) and (max-width:1024px) {
  .grid-33:nth-child(3n-2) {
    clear: none;
  }
  .tablet-grid-50:nth-child(2n-1) {
    clear: both;
  }
}
```
I think in the near future I will switch to a flex grid which should handle this issue.
