### ISSUE TITLE
Different gutter half for each breakpoints

### ISSUE THREAD

**Issue by Cedric-ruiu** [nathansmith/unsemantic#68]
Hi,

If we need a gutter-half 20px on desktop/tablet and 10px on mobile breakpoint, how can we do this? I thought several times but I did not find "clean" solution...

Cédric R.

**Comment by Aybee** [comment]
Did you try to put different paddings inside the media queries?
```css
*[class^='grid-'] {
  padding-left: 20px;
  padding-right: 20px;
}

@media (max-width: 767px) {
  *[class^='mobile-grid-'] {
    padding-left: 10px;
    padding-right: 10px;
  }
}
```
